#Face and Object Recognition Data Analysis
##Melisa Holdway and Brandy Bishop
###Eastern Oregon University

####Analysis

```{r}
dat=read.csv("RecognitionData.csv")
```
```{r}
str(dat)
```
```{r}
dat$Participant<-as.factor(dat$Participant)
```
```{r}
summary(aov(Scores~Condition+Error(Participant/Condition),data=dat))
```
```{r}
summary(aov(Scores~Condition*Age*Gender+Error(Participant/Condition), data=dat))
```
```{r}
t.test(dat$Scores[dat$"Condition"=="Face"],dat$Scores[dat$"Condition"=="Object"],var.equal=TRUE,paired=TRUE)
```
```{r}
mean(dat$Scores[dat$Condition=="Face"])
mean(dat$Scores[dat$Condition=="Object"])
sd(dat$Scores[dat$Condition=="Face"])
sd(dat$Scores[dat$Condition=="Object"])
```

####Figure

```{r}
library(ggplot2)
library(gplots)
library(dplyr)
```
```{r}
temp<-dat%>%group_by(Condition)%>%summarize(means=mean(Scores),
sems=sd(Scores)/sqrt(length(Scores)))
f<-ggplot(temp,aes(x=factor(Condition),y=means))+
geom_bar(stat="identity", color="black",
fill=c("blue", "red"))+
geom_errorbar(aes(ymax=means+sems,
ymin=means-sems),
width=.2)+
ggtitle("Recognition Rates")+
labs(x="Recognition Tasks",y="Mean Responses")+
scale_x_discrete(breaks=c("Face", "Object"),
labels=c("Face", "Object"))+
theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
theme(axis.title.y=element_text(size=12,face="bold",vjust=.25))+
theme(axis.text.x=element_text(size=10,face="bold",
color="black"))+
theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),
max(temp$means)+2*max(temp$sems)))+
theme(panel.border=element_blank(),axis.line=element_line())+
theme(panel.grid.major.x=element_blank())+
theme(panel.grid.major.y=element_line(color="darkgrey"))+
theme(panel.grid.minor.y=element_blank())
f
```
